---
logging:
  level:
    root: info
    home: debug
    org.springframework.security.oauth2: debug

delay:
  enabled: true
  millis-association: 500
  millis-offering: 500
  millis-person: 500

server:
  port: 8076

security:
  user:
    name: user
    password: secret

spring:
  mail:
    host: host.docker.internal
    port: 25
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: "http://mock-oidc/OIDC/introspect"
          client-id: home-client
          client-secret: secret

email:
  from: no-reply@home-institution-mock

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
      base-path: "/internal"
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true
  health:
    mail:
      enabled: false
  info:
    git:
      mode: full
    defaults:
      enabled: true
